version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      pac4j:
        patterns:
          - "org.pac4j*"
          - "pac4j-*"
    ignore:
      # Ignore pac4j pending https://groups.google.com/g/pac4j-dev/c/PgWtjlRwP4E
      - dependency-name: "org.pac4j:*"
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "daily"
